name: petcare_asgm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.6
  http: ^1.2.0
  csv: ^6.0.0
  sqflite: ^2.4.3
  path: ^1.9.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^13.0.0
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4          # For picking the image
  shared_preferences: ^2.5.5    # For saving text data
  path_provider: ^2.1.2         # For saving the image file
  flutter_local_notifications: ^22.3.0
  timezone: ^0.11.1
  camera: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/klinik.xlsx
    - assets/pharmaceutical_wholesalers.csv
